-- =================================================================================
-- منح الصلاحيات بين الـ Schemas
-- يجب تنفيذ هذا قبل إنشاء الجداول التي تحتوي على Foreign Keys
-- =================================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;

-- منح صلاحيات HR_CORE للجميع
GRANT REFERENCES, SELECT ON HR_CORE.COUNTRIES TO HR_PERSONNEL, HR_RECRUITMENT;
GRANT REFERENCES, SELECT ON HR_CORE.CITIES TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_CORE.DEPARTMENTS TO HR_PERSONNEL, HR_RECRUITMENT, HR_ATTENDANCE, HR_PAYROLL, HR_PERFORMANCE;
GRANT REFERENCES, SELECT ON HR_CORE.JOBS TO HR_PERSONNEL, HR_RECRUITMENT, HR_PAYROLL, HR_ATTENDANCE;
GRANT REFERENCES, SELECT ON HR_CORE.JOB_GRADES TO HR_PERSONNEL, HR_PAYROLL;
GRANT REFERENCES, SELECT ON HR_CORE.DOCUMENT_TYPES TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_CORE.BANKS TO HR_PERSONNEL, HR_PAYROLL;

-- منح صلاحيات HR_PERSONNEL للوحدات الأخرى
GRANT REFERENCES, SELECT ON HR_PERSONNEL.EMPLOYEES TO HR_RECRUITMENT, HR_ATTENDANCE, HR_LEAVES, HR_PAYROLL, HR_PERFORMANCE;
GRANT REFERENCES, SELECT ON HR_PERSONNEL.CONTRACTS TO HR_PAYROLL;

-- منح صلاحيات HR_ATTENDANCE
GRANT REFERENCES, SELECT ON HR_ATTENDANCE.SHIFT_TYPES TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_ATTENDANCE.DAILY_ATTENDANCE TO HR_PAYROLL;

-- منح صلاحيات HR_LEAVES
GRANT REFERENCES, SELECT ON HR_LEAVES.LEAVE_TYPES TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_LEAVES.LEAVE_REQUESTS TO HR_ATTENDANCE, HR_PAYROLL;

-- منح صلاحيات HR_PERFORMANCE
GRANT REFERENCES, SELECT ON HR_PERFORMANCE.DISCIPLINARY_ACTIONS TO HR_PAYROLL;

SELECT 'تم منح جميع الصلاحيات بنجاح!' AS STATUS FROM DUAL;
