-- Quick Drop Script for HRMS Database
-- WARNING: This will delete all data!

SET SERVEROUTPUT ON
SET ECHO ON

PROMPT Dropping all HRMS schemas...

DROP USER HR_PERFORMANCE CASCADE;
DROP USER HR_RECRUITMENT CASCADE;
DROP USER HR_PAYROLL CASCADE;
DROP USER HR_LEAVES CASCADE;
DROP USER HR_ATTENDANCE CASCADE;
DROP USER HR_PERSONNEL CASCADE;
DROP USER HR_CORE CASCADE;

PROMPT All schemas dropped successfully!
PROMPT You can now run: @00_MASTER_INSTALL.sql
