-- =================================================================================
-- Audit Triggers - النسخة النهائية التي تعمل 100%
-- تستخدم USER فقط - بدون أي dependencies
-- =================================================================================

-- 1. COUNTRIES
CREATE OR REPLACE TRIGGER HR_CORE.TRG_COUNTRIES_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.COUNTRIES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 2. CITIES
CREATE OR REPLACE TRIGGER HR_CORE.TRG_CITIES_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.CITIES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 3. BRANCHES
CREATE OR REPLACE TRIGGER HR_CORE.TRG_BRANCHES_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.BRANCHES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 4. DEPARTMENTS
CREATE OR REPLACE TRIGGER HR_CORE.TRG_DEPARTMENTS_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.DEPARTMENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 5. JOB_GRADES
CREATE OR REPLACE TRIGGER HR_CORE.TRG_JOB_GRADES_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.JOB_GRADES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 6. JOBS
CREATE OR REPLACE TRIGGER HR_CORE.TRG_JOBS_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.JOBS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 7. DOCUMENT_TYPES
CREATE OR REPLACE TRIGGER HR_CORE.TRG_DOCUMENT_TYPES_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.DOCUMENT_TYPES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 8. BANKS
CREATE OR REPLACE TRIGGER HR_CORE.TRG_BANKS_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.BANKS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

-- 9. SYSTEM_SETTINGS (إذا كان الجدول موجود)
CREATE OR REPLACE TRIGGER HR_CORE.TRG_SYSTEM_SETTINGS_AUDIT
BEFORE INSERT OR UPDATE ON HR_CORE.SYSTEM_SETTINGS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
        :NEW.CREATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := 1;
        :NEW.IS_DELETED := 0;
    END IF;
    IF UPDATING THEN
        :NEW.UPDATED_BY := USER;
        :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
        :NEW.VERSION_NO := NVL(:OLD.VERSION_NO, 0) + 1;
        :NEW.CREATED_BY := :OLD.CREATED_BY;
        :NEW.CREATED_AT := :OLD.CREATED_AT;
    END IF;
END;
/

PROMPT ========================================
PROMPT ✅ Audit Triggers Created!
PROMPT ========================================

-- التحقق
SELECT trigger_name, status 
FROM user_triggers 
WHERE trigger_name LIKE 'TRG_%AUDIT'
ORDER BY trigger_name;

PROMPT ========================================
PROMPT Expected: 9 Triggers - ENABLED
PROMPT ========================================
