-- =================================================================================
-- بيانات تجريبية - الجزء 1: HR_CORE
-- 3 صفوف لكل جدول
-- =================================================================================

ALTER SESSION SET CONTAINER = XEPDB1;

PROMPT ========================================
PROMPT إدخال بيانات HR_CORE
PROMPT ========================================

-- 1. COUNTRIES (الدول)
INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('المملكة العربية السعودية', 'Saudi Arabia', 'سعودي', 'SA', 'SYSTEM');

INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('مصر', 'Egypt', 'مصري', 'EG', 'SYSTEM');

INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('الأردن', 'Jordan', 'أردني', 'JO', 'SYSTEM');

-- 2. CITIES (المدن)
INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (1, 'الرياض', 'Riyadh', 'SYSTEM');

INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (1, 'جدة', 'Jeddah', 'SYSTEM');

INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (1, 'الدمام', 'Dammam', 'SYSTEM');

-- 3. BRANCHES (الفروع)
INSERT INTO HR_CORE.BRANCHES (BRANCH_NAME_AR, BRANCH_NAME_EN, CITY_ID, ADDRESS, CREATED_BY) 
VALUES ('الفرع الرئيسي', 'Main Branch', 1, 'طريق الملك فهد', 'SYSTEM');

INSERT INTO HR_CORE.BRANCHES (BRANCH_NAME_AR, BRANCH_NAME_EN, CITY_ID, ADDRESS, CREATED_BY) 
VALUES ('فرع جدة', 'Jeddah Branch', 2, 'طريق المدينة', 'SYSTEM');

INSERT INTO HR_CORE.BRANCHES (BRANCH_NAME_AR, BRANCH_NAME_EN, CITY_ID, ADDRESS, CREATED_BY) 
VALUES ('فرع الدمام', 'Dammam Branch', 3, 'طريق الخبر', 'SYSTEM');

-- 4. DEPARTMENTS (الأقسام)
INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم الموارد البشرية', 'Human Resources', 1, 'CC-HR-001', 1, 'SYSTEM');

INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم المالية', 'Finance Department', 1, 'CC-FIN-001', 1, 'SYSTEM');

INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم تقنية المعلومات', 'IT Department', 1, 'CC-IT-001', 1, 'SYSTEM');

-- 5. JOB_GRADES (الدرجات الوظيفية)
INSERT INTO HR_CORE.JOB_GRADES (GRADE_NAME, MIN_SALARY, MAX_SALARY, TICKET_CLASS, CREATED_BY) 
VALUES ('الدرجة الأولى', 15000, 25000, 'BUSINESS', 'SYSTEM');

INSERT INTO HR_CORE.JOB_GRADES (GRADE_NAME, MIN_SALARY, MAX_SALARY, TICKET_CLASS, CREATED_BY) 
VALUES ('الدرجة الثانية', 10000, 15000, 'ECONOMY', 'SYSTEM');

INSERT INTO HR_CORE.JOB_GRADES (GRADE_NAME, MIN_SALARY, MAX_SALARY, TICKET_CLASS, CREATED_BY) 
VALUES ('الدرجة الثالثة', 5000, 10000, 'ECONOMY', 'SYSTEM');

-- 6. JOBS (الوظائف)
INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('مدير موارد بشرية', 'HR Manager', 1, 0, 'SYSTEM');

INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('محاسب', 'Accountant', 2, 0, 'SYSTEM');

INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('مطور برمجيات', 'Software Developer', 2, 0, 'SYSTEM');

-- 7. DOCUMENT_TYPES (أنواع الوثائق)
INSERT INTO HR_CORE.DOCUMENT_TYPES (DOC_NAME_AR, IS_MANDATORY, REQUIRES_EXPIRY, ALERT_DAYS_BEFORE, CREATED_BY) 
VALUES ('الهوية الوطنية', 1, 1, 90, 'SYSTEM');

INSERT INTO HR_CORE.DOCUMENT_TYPES (DOC_NAME_AR, IS_MANDATORY, REQUIRES_EXPIRY, ALERT_DAYS_BEFORE, CREATED_BY) 
VALUES ('جواز السفر', 1, 1, 180, 'SYSTEM');

INSERT INTO HR_CORE.DOCUMENT_TYPES (DOC_NAME_AR, IS_MANDATORY, REQUIRES_EXPIRY, ALERT_DAYS_BEFORE, CREATED_BY) 
VALUES ('رخصة القيادة', 0, 1, 30, 'SYSTEM');

-- 8. BANKS (البنوك)
INSERT INTO HR_CORE.BANKS (BANK_NAME_AR, BANK_NAME_EN, BANK_CODE, CREATED_BY) 
VALUES ('البنك الأهلي', 'Al Ahli Bank', '10', 'SYSTEM');

INSERT INTO HR_CORE.BANKS (BANK_NAME_AR, BANK_NAME_EN, BANK_CODE, CREATED_BY) 
VALUES ('بنك الراجحي', 'Al Rajhi Bank', '80', 'SYSTEM');

INSERT INTO HR_CORE.BANKS (BANK_NAME_AR, BANK_NAME_EN, BANK_CODE, CREATED_BY) 
VALUES ('البنك السعودي الفرنسي', 'Banque Saudi Fransi', '55', 'SYSTEM');

-- 9. SYSTEM_SETTINGS (إعدادات النظام)
INSERT INTO HR_CORE.SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION_AR, IS_EDITABLE, CREATED_BY) 
VALUES ('COMPANY_NAME_AR', 'شركة إدارة الموارد البشرية', 'STRING', 'اسم الشركة بالعربي', 1, 'SYSTEM');

INSERT INTO HR_CORE.SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION_AR, IS_EDITABLE, CREATED_BY) 
VALUES ('WORKING_HOURS_PER_DAY', '8', 'NUMBER', 'ساعات العمل اليومية', 1, 'SYSTEM');

INSERT INTO HR_CORE.SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION_AR, IS_EDITABLE, CREATED_BY) 
VALUES ('ANNUAL_LEAVE_DAYS', '30', 'NUMBER', 'أيام الإجازة السنوية الافتراضية', 1, 'SYSTEM');

COMMIT;

PROMPT تم إدخال بيانات HR_CORE بنجاح

-- التحقق
SELECT 'COUNTRIES: ' || COUNT(*) FROM HR_CORE.COUNTRIES
UNION ALL
SELECT 'CITIES: ' || COUNT(*) FROM HR_CORE.CITIES
UNION ALL
SELECT 'BRANCHES: ' || COUNT(*) FROM HR_CORE.BRANCHES
UNION ALL
SELECT 'DEPARTMENTS: ' || COUNT(*) FROM HR_CORE.DEPARTMENTS
UNION ALL
SELECT 'JOB_GRADES: ' || COUNT(*) FROM HR_CORE.JOB_GRADES
UNION ALL
SELECT 'JOBS: ' || COUNT(*) FROM HR_CORE.JOBS
UNION ALL
SELECT 'DOCUMENT_TYPES: ' || COUNT(*) FROM HR_CORE.DOCUMENT_TYPES
UNION ALL
SELECT 'BANKS: ' || COUNT(*) FROM HR_CORE.BANKS
UNION ALL
SELECT 'SYSTEM_SETTINGS: ' || COUNT(*) FROM HR_CORE.SYSTEM_SETTINGS;
