-- =================================================================================
-- إضافة بيانات إضافية لـ HR_CORE
-- =================================================================================

ALTER SESSION SET CONTAINER = XEPDB1;

PROMPT ========================================
PROMPT إضافة بيانات إضافية لـ HR_CORE
PROMPT ========================================

-- إضافة دول إضافية
INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('الإمارات العربية المتحدة', 'United Arab Emirates', 'إماراتي', 'AE', 'SYSTEM');

INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('الكويت', 'Kuwait', 'كويتي', 'KW', 'SYSTEM');

INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('البحرين', 'Bahrain', 'بحريني', 'BH', 'SYSTEM');

INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('قطر', 'Qatar', 'قطري', 'QA', 'SYSTEM');

INSERT INTO HR_CORE.COUNTRIES (COUNTRY_NAME_AR, COUNTRY_NAME_EN, CITIZENSHIP_NAME_AR, ISO_CODE, CREATED_BY) 
VALUES ('عُمان', 'Oman', 'عُماني', 'OM', 'SYSTEM');

-- إضافة مدن إضافية
INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (1, 'مكة المكرمة', 'Makkah', 'SYSTEM');

INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (1, 'المدينة المنورة', 'Madinah', 'SYSTEM');

INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (1, 'الخبر', 'Khobar', 'SYSTEM');

INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (4, 'دبي', 'Dubai', 'SYSTEM');

INSERT INTO HR_CORE.CITIES (COUNTRY_ID, CITY_NAME_AR, CITY_NAME_EN, CREATED_BY) 
VALUES (4, 'أبوظبي', 'Abu Dhabi', 'SYSTEM');

-- إضافة درجات وظيفية إضافية
INSERT INTO HR_CORE.JOB_GRADES (GRADE_NAME, MIN_SALARY, MAX_SALARY, TICKET_CLASS, CREATED_BY) 
VALUES ('الدرجة الرابعة', 3000, 5000, 'ECONOMY', 'SYSTEM');

INSERT INTO HR_CORE.JOB_GRADES (GRADE_NAME, MIN_SALARY, MAX_SALARY, TICKET_CLASS, CREATED_BY) 
VALUES ('الدرجة الخامسة', 2000, 3000, 'ECONOMY', 'SYSTEM');

-- إضافة وظائف إضافية
INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('طبيب عام', 'General Practitioner', 1, 1, 'SYSTEM');

INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('ممرض', 'Nurse', 2, 1, 'SYSTEM');

INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('صيدلي', 'Pharmacist', 2, 1, 'SYSTEM');

INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('مساعد إداري', 'Administrative Assistant', 3, 0, 'SYSTEM');

INSERT INTO HR_CORE.JOBS (JOB_TITLE_AR, JOB_TITLE_EN, DEFAULT_GRADE_ID, IS_MEDICAL, CREATED_BY) 
VALUES ('موظف استقبال', 'Receptionist', 4, 0, 'SYSTEM');

-- إضافة أقسام إضافية
INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم الطوارئ', 'Emergency Department', 1, 'CC-EMER-001', 1, 'SYSTEM');

INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم الجراحة', 'Surgery Department', 1, 'CC-SURG-001', 1, 'SYSTEM');

INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم الأطفال', 'Pediatrics Department', 1, 'CC-PEDI-001', 1, 'SYSTEM');

INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم الأشعة', 'Radiology Department', 1, 'CC-RADI-001', 1, 'SYSTEM');

INSERT INTO HR_CORE.DEPARTMENTS (DEPT_NAME_AR, DEPT_NAME_EN, BRANCH_ID, COST_CENTER_CODE, IS_ACTIVE, CREATED_BY) 
VALUES ('قسم المختبر', 'Laboratory Department', 1, 'CC-LAB-001', 1, 'SYSTEM');

-- إضافة أنواع وثائق إضافية
INSERT INTO HR_CORE.DOCUMENT_TYPES (DOC_NAME_AR, IS_MANDATORY, REQUIRES_EXPIRY, ALERT_DAYS_BEFORE, CREATED_BY) 
VALUES ('شهادة التأمين الطبي', 1, 1, 60, 'SYSTEM');

INSERT INTO HR_CORE.DOCUMENT_TYPES (DOC_NAME_AR, IS_MANDATORY, REQUIRES_EXPIRY, ALERT_DAYS_BEFORE, CREATED_BY) 
VALUES ('رخصة مزاولة المهنة', 1, 1, 90, 'SYSTEM');

INSERT INTO HR_CORE.DOCUMENT_TYPES (DOC_NAME_AR, IS_MANDATORY, REQUIRES_EXPIRY, ALERT_DAYS_BEFORE, CREATED_BY) 
VALUES ('شهادة حسن السيرة والسلوك', 0, 0, 0, 'SYSTEM');

-- إضافة بنوك إضافية
INSERT INTO HR_CORE.BANKS (BANK_NAME_AR, BANK_NAME_EN, BANK_CODE, CREATED_BY) 
VALUES ('بنك الرياض', 'Riyad Bank', '20', 'SYSTEM');

INSERT INTO HR_CORE.BANKS (BANK_NAME_AR, BANK_NAME_EN, BANK_CODE, CREATED_BY) 
VALUES ('البنك السعودي البريطاني', 'SABB', '45', 'SYSTEM');

INSERT INTO HR_CORE.BANKS (BANK_NAME_AR, BANK_NAME_EN, BANK_CODE, CREATED_BY) 
VALUES ('بنك الإنماء', 'Alinma Bank', '05', 'SYSTEM');

-- إضافة إعدادات نظام إضافية
INSERT INTO HR_CORE.SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION_AR, IS_EDITABLE, CREATED_BY) 
VALUES ('COMPANY_NAME_EN', 'HR Management System', 'STRING', 'اسم الشركة بالإنجليزي', 1, 'SYSTEM');

INSERT INTO HR_CORE.SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION_AR, IS_EDITABLE, CREATED_BY) 
VALUES ('WORKING_DAYS_PER_WEEK', '5', 'NUMBER', 'أيام العمل في الأسبوع', 1, 'SYSTEM');

INSERT INTO HR_CORE.SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION_AR, IS_EDITABLE, CREATED_BY) 
VALUES ('PROBATION_PERIOD_DAYS', '90', 'NUMBER', 'فترة التجربة بالأيام', 1, 'SYSTEM');

INSERT INTO HR_CORE.SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION_AR, IS_EDITABLE, CREATED_BY) 
VALUES ('MAX_OVERTIME_HOURS_PER_MONTH', '40', 'NUMBER', 'الحد الأقصى لساعات العمل الإضافي شهرياً', 1, 'SYSTEM');

COMMIT;

PROMPT ========================================
PROMPT تم إضافة البيانات بنجاح
PROMPT ========================================

-- عرض ملخص البيانات
SELECT 'COUNTRIES: ' || COUNT(*) AS SUMMARY FROM HR_CORE.COUNTRIES
UNION ALL
SELECT 'CITIES: ' || COUNT(*) FROM HR_CORE.CITIES
UNION ALL
SELECT 'BRANCHES: ' || COUNT(*) FROM HR_CORE.BRANCHES
UNION ALL
SELECT 'DEPARTMENTS: ' || COUNT(*) FROM HR_CORE.DEPARTMENTS
UNION ALL
SELECT 'JOB_GRADES: ' || COUNT(*) FROM HR_CORE.JOB_GRADES
UNION ALL
SELECT 'JOBS: ' || COUNT(*) FROM HR_CORE.JOBS
UNION ALL
SELECT 'DOCUMENT_TYPES: ' || COUNT(*) FROM HR_CORE.DOCUMENT_TYPES
UNION ALL
SELECT 'BANKS: ' || COUNT(*) FROM HR_CORE.BANKS
UNION ALL
SELECT 'SYSTEM_SETTINGS: ' || COUNT(*) FROM HR_CORE.SYSTEM_SETTINGS;
