-- =================================================================================
-- بيانات تجريبية - الجزء 2: HR_PERSONNEL
-- 3 موظفين مع بياناتهم الكاملة
-- =================================================================================

ALTER SESSION SET CONTAINER = XEPDB1;

PROMPT ========================================
PROMPT إدخال بيانات HR_PERSONNEL
PROMPT ========================================

-- 1. EMPLOYEES (الموظفين)
INSERT INTO HR_PERSONNEL.EMPLOYEES (
    EMPLOYEE_NUMBER, FIRST_NAME_AR, SECOND_NAME_AR, THIRD_NAME_AR, HIJRI_LAST_NAME_AR, FULL_NAME_EN,
    GENDER, BIRTH_DATE, MARITAL_STATUS, NATIONALITY_ID, JOB_ID, DEPT_ID, JOINING_DATE, STATUS,
    EMAIL, MOBILE, CREATED_BY
) VALUES (
    '20260001', 'أحمد', 'محمد', 'عبدالله', 'السعيد', 'Ahmed Mohammed Abdullah Alsaeed',
    'M', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'MARRIED', 1, 1, 1, TO_DATE('2020-01-01', 'YYYY-MM-DD'), 'ACTIVE',
    'ahmed.alsaeed@company.com', '0501234567', 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMPLOYEES (
    EMPLOYEE_NUMBER, FIRST_NAME_AR, SECOND_NAME_AR, THIRD_NAME_AR, HIJRI_LAST_NAME_AR, FULL_NAME_EN,
    GENDER, BIRTH_DATE, MARITAL_STATUS, NATIONALITY_ID, JOB_ID, DEPT_ID, JOINING_DATE, STATUS,
    EMAIL, MOBILE, CREATED_BY
) VALUES (
    '20260002', 'فاطمة', 'علي', 'حسن', 'الزهراني', 'Fatima Ali Hassan Alzahrani',
    'F', TO_DATE('1992-08-20', 'YYYY-MM-DD'), 'SINGLE', 1, 2, 2, TO_DATE('2021-03-15', 'YYYY-MM-DD'), 'ACTIVE',
    'fatima.alzahrani@company.com', '0509876543', 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMPLOYEES (
    EMPLOYEE_NUMBER, FIRST_NAME_AR, SECOND_NAME_AR, THIRD_NAME_AR, HIJRI_LAST_NAME_AR, FULL_NAME_EN,
    GENDER, BIRTH_DATE, MARITAL_STATUS, NATIONALITY_ID, JOB_ID, DEPT_ID, JOINING_DATE, STATUS,
    EMAIL, MOBILE, CREATED_BY
) VALUES (
    '20260003', 'خالد', 'عبدالرحمن', 'سعد', 'القحطاني', 'Khaled Abdulrahman Saad Alqahtani',
    'M', TO_DATE('1988-12-10', 'YYYY-MM-DD'), 'MARRIED', 1, 3, 3, TO_DATE('2019-06-01', 'YYYY-MM-DD'), 'ACTIVE',
    'khaled.alqahtani@company.com', '0551122334', 'SYSTEM'
);

-- 2. CONTRACTS (العقود)
INSERT INTO HR_PERSONNEL.CONTRACTS (
    EMPLOYEE_ID, CONTRACT_TYPE, START_DATE, END_DATE, IS_RENEWABLE,
    BASIC_SALARY, HOUSING_ALLOWANCE, TRANSPORT_ALLOWANCE, OTHER_ALLOWANCES,
    VACATION_DAYS, WORKING_HOURS_DAILY, CONTRACT_STATUS, CREATED_BY
) VALUES (
    1, 'FULL_TIME', TO_DATE('2020-01-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'), 1,
    20000, 5000, 1500, 500, 30, 8, 'ACTIVE', 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.CONTRACTS (
    EMPLOYEE_ID, CONTRACT_TYPE, START_DATE, END_DATE, IS_RENEWABLE,
    BASIC_SALARY, HOUSING_ALLOWANCE, TRANSPORT_ALLOWANCE, OTHER_ALLOWANCES,
    VACATION_DAYS, WORKING_HOURS_DAILY, CONTRACT_STATUS, CREATED_BY
) VALUES (
    2, 'FULL_TIME', TO_DATE('2021-03-15', 'YYYY-MM-DD'), TO_DATE('2026-03-14', 'YYYY-MM-DD'), 1,
    12000, 3000, 1000, 300, 30, 8, 'ACTIVE', 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.CONTRACTS (
    EMPLOYEE_ID, CONTRACT_TYPE, START_DATE, END_DATE, IS_RENEWABLE,
    BASIC_SALARY, HOUSING_ALLOWANCE, TRANSPORT_ALLOWANCE, OTHER_ALLOWANCES,
    VACATION_DAYS, WORKING_HOURS_DAILY, CONTRACT_STATUS, CREATED_BY
) VALUES (
    3, 'FULL_TIME', TO_DATE('2019-06-01', 'YYYY-MM-DD'), TO_DATE('2024-05-31', 'YYYY-MM-DD'), 1,
    15000, 3750, 1200, 400, 30, 8, 'ACTIVE', 'SYSTEM'
);

-- 3. EMPLOYEE_DOCUMENTS (الوثائق)
INSERT INTO HR_PERSONNEL.EMPLOYEE_DOCUMENTS (
    EMPLOYEE_ID, DOC_TYPE_ID, DOC_NUMBER, ISSUE_DATE, EXPIRY_DATE, ISSUE_PLACE, IS_ACTIVE, CREATED_BY
) VALUES (
    1, 1, '1234567890', TO_DATE('2015-01-01', 'YYYY-MM-DD'), TO_DATE('2030-01-01', 'YYYY-MM-DD'), 'الرياض', 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMPLOYEE_DOCUMENTS (
    EMPLOYEE_ID, DOC_TYPE_ID, DOC_NUMBER, ISSUE_DATE, EXPIRY_DATE, ISSUE_PLACE, IS_ACTIVE, CREATED_BY
) VALUES (
    2, 1, '2345678901', TO_DATE('2016-05-10', 'YYYY-MM-DD'), TO_DATE('2031-05-10', 'YYYY-MM-DD'), 'جدة', 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMPLOYEE_DOCUMENTS (
    EMPLOYEE_ID, DOC_TYPE_ID, DOC_NUMBER, ISSUE_DATE, EXPIRY_DATE, ISSUE_PLACE, IS_ACTIVE, CREATED_BY
) VALUES (
    3, 2, 'P9876543', TO_DATE('2018-03-15', 'YYYY-MM-DD'), TO_DATE('2028-03-15', 'YYYY-MM-DD'), 'الدمام', 1, 'SYSTEM'
);

-- 4. EMPLOYEE_BANK_ACCOUNTS (الحسابات البنكية)
INSERT INTO HR_PERSONNEL.EMPLOYEE_BANK_ACCOUNTS (
    EMPLOYEE_ID, BANK_ID, ACCOUNT_NUMBER, IBAN, IS_PRIMARY, IS_ACTIVE, CREATED_BY
) VALUES (
    1, 1, '1234567890123', 'SA0310000001234567890123', 1, 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMPLOYEE_BANK_ACCOUNTS (
    EMPLOYEE_ID, BANK_ID, ACCOUNT_NUMBER, IBAN, IS_PRIMARY, IS_ACTIVE, CREATED_BY
) VALUES (
    2, 2, '9876543210987', 'SA0380000009876543210987', 1, 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMPLOYEE_BANK_ACCOUNTS (
    EMPLOYEE_ID, BANK_ID, ACCOUNT_NUMBER, IBAN, IS_PRIMARY, IS_ACTIVE, CREATED_BY
) VALUES (
    3, 3, '5555666677778', 'SA0355000005555666677778', 1, 1, 'SYSTEM'
);

-- 5. EMERGENCY_CONTACTS (جهات الطوارئ)
INSERT INTO HR_PERSONNEL.EMERGENCY_CONTACTS (
    EMPLOYEE_ID, CONTACT_NAME_AR, RELATIONSHIP, PHONE_PRIMARY, IS_PRIMARY, CREATED_BY
) VALUES (
    1, 'محمد عبدالله السعيد', 'أب', '0501111111', 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMERGENCY_CONTACTS (
    EMPLOYEE_ID, CONTACT_NAME_AR, RELATIONSHIP, PHONE_PRIMARY, IS_PRIMARY, CREATED_BY
) VALUES (
    2, 'علي حسن الزهراني', 'أخ', '0502222222', 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.EMERGENCY_CONTACTS (
    EMPLOYEE_ID, CONTACT_NAME_AR, RELATIONSHIP, PHONE_PRIMARY, IS_PRIMARY, CREATED_BY
) VALUES (
    3, 'نورة سعد القحطاني', 'زوجة', '0503333333', 1, 'SYSTEM'
);

-- 6. DEPENDENTS (التابعين)
INSERT INTO HR_PERSONNEL.DEPENDENTS (
    EMPLOYEE_ID, NAME_AR, RELATIONSHIP, BIRTH_DATE, IS_ELIGIBLE_FOR_TICKET, IS_ELIGIBLE_FOR_INSURANCE, CREATED_BY
) VALUES (
    1, 'سارة أحمد السعيد', 'ابنة', TO_DATE('2015-03-10', 'YYYY-MM-DD'), 1, 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.DEPENDENTS (
    EMPLOYEE_ID, NAME_AR, RELATIONSHIP, BIRTH_DATE, IS_ELIGIBLE_FOR_TICKET, IS_ELIGIBLE_FOR_INSURANCE, CREATED_BY
) VALUES (
    1, 'عبدالله أحمد السعيد', 'ابن', TO_DATE('2018-07-20', 'YYYY-MM-DD'), 1, 1, 'SYSTEM'
);

INSERT INTO HR_PERSONNEL.DEPENDENTS (
    EMPLOYEE_ID, NAME_AR, RELATIONSHIP, BIRTH_DATE, IS_ELIGIBLE_FOR_TICKET, IS_ELIGIBLE_FOR_INSURANCE, CREATED_BY
) VALUES (
    3, 'ريم خالد القحطاني', 'ابنة', TO_DATE('2020-01-15', 'YYYY-MM-DD'), 1, 1, 'SYSTEM'
);

COMMIT;

PROMPT تم إدخال بيانات HR_PERSONNEL بنجاح

-- التحقق
SELECT 'EMPLOYEES: ' || COUNT(*) FROM HR_PERSONNEL.EMPLOYEES
UNION ALL
SELECT 'CONTRACTS: ' || COUNT(*) FROM HR_PERSONNEL.CONTRACTS
UNION ALL
SELECT 'EMPLOYEE_DOCUMENTS: ' || COUNT(*) FROM HR_PERSONNEL.EMPLOYEE_DOCUMENTS
UNION ALL
SELECT 'EMPLOYEE_BANK_ACCOUNTS: ' || COUNT(*) FROM HR_PERSONNEL.EMPLOYEE_BANK_ACCOUNTS
UNION ALL
SELECT 'EMERGENCY_CONTACTS: ' || COUNT(*) FROM HR_PERSONNEL.EMERGENCY_CONTACTS
UNION ALL
SELECT 'DEPENDENTS: ' || COUNT(*) FROM HR_PERSONNEL.DEPENDENTS;
