-- =================================================================================
-- بيانات تجريبية - الجزء 3: HR_ATTENDANCE, HR_LEAVES, HR_PAYROLL
-- =================================================================================

ALTER SESSION SET CONTAINER = XEPDB1;

PROMPT ========================================
PROMPT إدخال بيانات HR_ATTENDANCE
PROMPT ========================================

-- SHIFT_TYPES (أنواع المناوبات)
INSERT INTO HR_ATTENDANCE.SHIFT_TYPES (SHIFT_NAME_AR, START_TIME, END_TIME, HOURS_COUNT, IS_CROSS_DAY, GRACE_PERIOD_MINS, CREATED_BY)
VALUES ('الفترة الصباحية', '08:00', '16:00', 8, 0, 15, 'SYSTEM');

INSERT INTO HR_ATTENDANCE.SHIFT_TYPES (SHIFT_NAME_AR, START_TIME, END_TIME, HOURS_COUNT, IS_CROSS_DAY, GRACE_PERIOD_MINS, CREATED_BY)
VALUES ('الفترة المسائية', '14:00', '22:00', 8, 0, 15, 'SYSTEM');

INSERT INTO HR_ATTENDANCE.SHIFT_TYPES (SHIFT_NAME_AR, START_TIME, END_TIME, HOURS_COUNT, IS_CROSS_DAY, GRACE_PERIOD_MINS, CREATED_BY)
VALUES ('الفترة الليلية', '22:00', '06:00', 8, 1, 15, 'SYSTEM');

-- DAILY_ATTENDANCE (الحضور اليومي)
INSERT INTO HR_ATTENDANCE.DAILY_ATTENDANCE (
    EMPLOYEE_ID, ATTENDANCE_DATE, PLANNED_SHIFT_ID, ACTUAL_IN_TIME, ACTUAL_OUT_TIME,
    LATE_MINUTES, EARLY_LEAVE_MINUTES, OVERTIME_MINUTES, STATUS, CREATED_BY
) VALUES (
    1, TO_DATE('2026-01-15', 'YYYY-MM-DD'), 1, 
    TO_TIMESTAMP('2026-01-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-01-15 16:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    0, 0, 0, 'PRESENT', 'SYSTEM'
);

INSERT INTO HR_ATTENDANCE.DAILY_ATTENDANCE (
    EMPLOYEE_ID, ATTENDANCE_DATE, PLANNED_SHIFT_ID, ACTUAL_IN_TIME, ACTUAL_OUT_TIME,
    LATE_MINUTES, EARLY_LEAVE_MINUTES, OVERTIME_MINUTES, STATUS, CREATED_BY
) VALUES (
    2, TO_DATE('2026-01-15', 'YYYY-MM-DD'), 1,
    TO_TIMESTAMP('2026-01-15 08:10:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-01-15 16:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    10, 0, 0, 'PRESENT', 'SYSTEM'
);

INSERT INTO HR_ATTENDANCE.DAILY_ATTENDANCE (
    EMPLOYEE_ID, ATTENDANCE_DATE, PLANNED_SHIFT_ID, ACTUAL_IN_TIME, ACTUAL_OUT_TIME,
    LATE_MINUTES, EARLY_LEAVE_MINUTES, OVERTIME_MINUTES, STATUS, CREATED_BY
) VALUES (
    3, TO_DATE('2026-01-15', 'YYYY-MM-DD'), 1,
    TO_TIMESTAMP('2026-01-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_TIMESTAMP('2026-01-15 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    0, 0, 60, 'PRESENT', 'SYSTEM'
);

PROMPT ========================================
PROMPT إدخال بيانات HR_LEAVES
PROMPT ========================================

-- LEAVE_TYPES (أنواع الإجازات)
INSERT INTO HR_LEAVES.LEAVE_TYPES (LEAVE_NAME_AR, IS_PAID, MAX_DAYS_PER_YEAR, REQUIRES_ATTACHMENT, IS_CARRY_FORWARD, CREATED_BY)
VALUES ('إجازة سنوية', 1, 30, 0, 1, 'SYSTEM');

INSERT INTO HR_LEAVES.LEAVE_TYPES (LEAVE_NAME_AR, IS_PAID, MAX_DAYS_PER_YEAR, REQUIRES_ATTACHMENT, IS_CARRY_FORWARD, CREATED_BY)
VALUES ('إجازة مرضية', 1, 15, 1, 0, 'SYSTEM');

INSERT INTO HR_LEAVES.LEAVE_TYPES (LEAVE_NAME_AR, IS_PAID, MAX_DAYS_PER_YEAR, REQUIRES_ATTACHMENT, IS_CARRY_FORWARD, CREATED_BY)
VALUES ('إجازة بدون راتب', 0, 90, 0, 0, 'SYSTEM');

-- EMPLOYEE_LEAVE_BALANCES (أرصدة الإجازات)
INSERT INTO HR_LEAVES.EMPLOYEE_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_TYPE_ID, CURRENT_BALANCE, YEAR, CREATED_BY)
VALUES (1, 1, 30, 2026, 'SYSTEM');

INSERT INTO HR_LEAVES.EMPLOYEE_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_TYPE_ID, CURRENT_BALANCE, YEAR, CREATED_BY)
VALUES (2, 1, 30, 2026, 'SYSTEM');

INSERT INTO HR_LEAVES.EMPLOYEE_LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_TYPE_ID, CURRENT_BALANCE, YEAR, CREATED_BY)
VALUES (3, 1, 25, 2026, 'SYSTEM');

-- LEAVE_REQUESTS (طلبات الإجازة)
INSERT INTO HR_LEAVES.LEAVE_REQUESTS (
    EMPLOYEE_ID, LEAVE_TYPE_ID, START_DATE, END_DATE, DAYS_COUNT, REASON, STATUS, CREATED_BY
) VALUES (
    1, 1, TO_DATE('2026-02-01', 'YYYY-MM-DD'), TO_DATE('2026-02-05', 'YYYY-MM-DD'), 
    5, 'إجازة عائلية', 'PENDING', 'SYSTEM'
);

INSERT INTO HR_LEAVES.LEAVE_REQUESTS (
    EMPLOYEE_ID, LEAVE_TYPE_ID, START_DATE, END_DATE, DAYS_COUNT, REASON, STATUS, CREATED_BY
) VALUES (
    2, 2, TO_DATE('2026-01-20', 'YYYY-MM-DD'), TO_DATE('2026-01-22', 'YYYY-MM-DD'),
    3, 'إجازة مرضية', 'HR_APPROVED', 'SYSTEM'
);

INSERT INTO HR_LEAVES.LEAVE_REQUESTS (
    EMPLOYEE_ID, LEAVE_TYPE_ID, START_DATE, END_DATE, DAYS_COUNT, REASON, STATUS, CREATED_BY
) VALUES (
    3, 1, TO_DATE('2026-03-10', 'YYYY-MM-DD'), TO_DATE('2026-03-14', 'YYYY-MM-DD'),
    5, 'إجازة سنوية', 'MANAGER_APPROVED', 'SYSTEM'
);

PROMPT ========================================
PROMPT إدخال بيانات HR_PAYROLL
PROMPT ========================================

-- SALARY_ELEMENTS (بنود الراتب)
INSERT INTO HR_PAYROLL.SALARY_ELEMENTS (ELEMENT_NAME_AR, ELEMENT_TYPE, IS_TAXABLE, IS_GOSI_BASE, IS_RECURRING, CREATED_BY)
VALUES ('الراتب الأساسي', 'EARNING', 0, 1, 1, 'SYSTEM');

INSERT INTO HR_PAYROLL.SALARY_ELEMENTS (ELEMENT_NAME_AR, ELEMENT_TYPE, IS_TAXABLE, IS_GOSI_BASE, IS_RECURRING, CREATED_BY)
VALUES ('بدل السكن', 'EARNING', 0, 0, 1, 'SYSTEM');

INSERT INTO HR_PAYROLL.SALARY_ELEMENTS (ELEMENT_NAME_AR, ELEMENT_TYPE, IS_TAXABLE, IS_GOSI_BASE, IS_RECURRING, CREATED_BY)
VALUES ('التأمينات الاجتماعية', 'DEDUCTION', 0, 0, 1, 'SYSTEM');

-- PAYROLL_RUNS (مسيرات الرواتب)
INSERT INTO HR_PAYROLL.PAYROLL_RUNS (YEAR, MONTH, RUN_DATE, STATUS, TOTAL_PAYOUT, CREATED_BY)
VALUES (2026, 1, TO_DATE('2026-01-25', 'YYYY-MM-DD'), 'APPROVED', 141000, 'SYSTEM');

INSERT INTO HR_PAYROLL.PAYROLL_RUNS (YEAR, MONTH, RUN_DATE, STATUS, TOTAL_PAYOUT, CREATED_BY)
VALUES (2025, 12, TO_DATE('2025-12-25', 'YYYY-MM-DD'), 'PAID', 141000, 'SYSTEM');

INSERT INTO HR_PAYROLL.PAYROLL_RUNS (YEAR, MONTH, RUN_DATE, STATUS, TOTAL_PAYOUT, CREATED_BY)
VALUES (2026, 2, TO_DATE('2026-02-25', 'YYYY-MM-DD'), 'DRAFT', 0, 'SYSTEM');

-- PAYSLIPS (قسائم الرواتب)
INSERT INTO HR_PAYROLL.PAYSLIPS (
    RUN_ID, EMPLOYEE_ID, BASIC_SALARY, TOTAL_ALLOWANCES, TOTAL_DEDUCTIONS, NET_SALARY, CREATED_BY
) VALUES (
    1, 1, 20000, 7000, 2000, 25000, 'SYSTEM'
);

INSERT INTO HR_PAYROLL.PAYSLIPS (
    RUN_ID, EMPLOYEE_ID, BASIC_SALARY, TOTAL_ALLOWANCES, TOTAL_DEDUCTIONS, NET_SALARY, CREATED_BY
) VALUES (
    1, 2, 12000, 4300, 1200, 15100, 'SYSTEM'
);

INSERT INTO HR_PAYROLL.PAYSLIPS (
    RUN_ID, EMPLOYEE_ID, BASIC_SALARY, TOTAL_ALLOWANCES, TOTAL_DEDUCTIONS, NET_SALARY, CREATED_BY
) VALUES (
    1, 3, 15000, 5350, 1500, 18850, 'SYSTEM'
);

COMMIT;

PROMPT ========================================
PROMPT تم إدخال جميع البيانات التجريبية بنجاح!
PROMPT ========================================

-- التحقق النهائي
SELECT 'HR_ATTENDANCE.SHIFT_TYPES: ' || COUNT(*) FROM HR_ATTENDANCE.SHIFT_TYPES
UNION ALL
SELECT 'HR_ATTENDANCE.DAILY_ATTENDANCE: ' || COUNT(*) FROM HR_ATTENDANCE.DAILY_ATTENDANCE
UNION ALL
SELECT 'HR_LEAVES.LEAVE_TYPES: ' || COUNT(*) FROM HR_LEAVES.LEAVE_TYPES
UNION ALL
SELECT 'HR_LEAVES.EMPLOYEE_LEAVE_BALANCES: ' || COUNT(*) FROM HR_LEAVES.EMPLOYEE_LEAVE_BALANCES
UNION ALL
SELECT 'HR_LEAVES.LEAVE_REQUESTS: ' || COUNT(*) FROM HR_LEAVES.LEAVE_REQUESTS
UNION ALL
SELECT 'HR_PAYROLL.SALARY_ELEMENTS: ' || COUNT(*) FROM HR_PAYROLL.SALARY_ELEMENTS
UNION ALL
SELECT 'HR_PAYROLL.PAYROLL_RUNS: ' || COUNT(*) FROM HR_PAYROLL.PAYROLL_RUNS
UNION ALL
SELECT 'HR_PAYROLL.PAYSLIPS: ' || COUNT(*) FROM HR_PAYROLL.PAYSLIPS;



