SELECT 
    e.EMPLOYEE_NUMBER,
    e.FULL_NAME_EN,
    j.JOB_TITLE_AR,
    d.DEPT_NAME_AR,
    c.BASIC_SALARY
FROM HR_PERSONNEL.EMPLOYEES e
JOIN HR_CORE.JOBS j ON e.JOB_ID = j.JOB_ID
JOIN HR_CORE.DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
JOIN HR_PERSONNEL.CONTRACTS c ON e.EMPLOYEE_ID = c.EMPLOYEE_ID
WHERE e.STATUS = 'ACTIVE';