-- =================================================================================
-- منح صلاحيات للجداول الإضافية
-- يجب تنفيذه قبل إضافة Foreign Keys
-- =================================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;

-- منح صلاحيات HR_PERSONNEL للجداول الجديدة
GRANT REFERENCES, SELECT ON HR_PERSONNEL.EMPLOYEES TO HR_CORE;
GRANT REFERENCES, SELECT ON HR_CORE.DEPARTMENTS TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_CORE.JOBS TO HR_PERSONNEL;

-- منح صلاحيات للجداول الجديدة
GRANT REFERENCES, SELECT ON HR_CORE.SYSTEM_USERS TO HR_CORE;
GRANT REFERENCES, SELECT ON HR_CORE.SYSTEM_ROLES TO HR_CORE;
GRANT REFERENCES, SELECT ON HR_CORE.SYSTEM_PERMISSIONS TO HR_CORE;
GRANT REFERENCES, SELECT ON HR_CORE.ASSET_CATEGORIES TO HR_CORE;
GRANT REFERENCES, SELECT ON HR_CORE.COMPANY_ASSETS TO HR_PERSONNEL;

GRANT REFERENCES, SELECT ON HR_PERSONNEL.TRAINING_COURSES TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_PAYROLL.INSURANCE_PLANS TO HR_PAYROLL;
GRANT REFERENCES, SELECT ON HR_PAYROLL.PAYROLL_RUNS TO HR_PAYROLL;

SELECT 'تم منح الصلاحيات للجداول الإضافية بنجاح!' AS STATUS FROM DUAL;
