-- =================================================================================
-- إضافة Foreign Keys للجداول الإضافية (14 جدول)
-- مع التحقق من عدم وجودها مسبقاً
-- =================================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;

PROMPT ========================================
PROMPT إضافة Foreign Keys للجداول الجديدة
PROMPT ========================================

-- حذف Foreign Keys القديمة إن وجدت (لتجنب التكرار)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_CORE.SYSTEM_USERS DROP CONSTRAINT FK_USER_EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_CORE.USER_ROLES DROP CONSTRAINT FK_UR_USER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_CORE.USER_ROLES DROP CONSTRAINT FK_UR_ROLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_CORE.ROLE_PERMISSIONS DROP CONSTRAINT FK_RP_ROLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_CORE.ROLE_PERMISSIONS DROP CONSTRAINT FK_RP_PERM';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRAINING DROP CONSTRAINT FK_TRAIN_EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRAINING DROP CONSTRAINT FK_TRAIN_COURSE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PAYROLL.EMPLOYEE_INSURANCE DROP CONSTRAINT FK_INS_EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PAYROLL.EMPLOYEE_INSURANCE DROP CONSTRAINT FK_INS_PLAN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PAYROLL.BONUSES DROP CONSTRAINT FK_BONUS_EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PAYROLL.BONUSES DROP CONSTRAINT FK_BONUS_APPROVER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PAYROLL.BONUSES DROP CONSTRAINT FK_BONUS_RUN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_CORE.COMPANY_ASSETS DROP CONSTRAINT FK_ASSET_CAT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_ASSETS DROP CONSTRAINT FK_EASSET_EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_ASSETS DROP CONSTRAINT FK_EASSET_ASSET';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS DROP CONSTRAINT FK_TRANS_EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS DROP CONSTRAINT FK_TRANS_FROM_DEPT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS DROP CONSTRAINT FK_TRANS_TO_DEPT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS DROP CONSTRAINT FK_TRANS_FROM_JOB';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS DROP CONSTRAINT FK_TRANS_TO_JOB';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS DROP CONSTRAINT FK_TRANS_APPROVER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- الآن إضافة Foreign Keys الجديدة
PROMPT إضافة Foreign Keys...

-- Foreign Keys لجداول الأمان
ALTER TABLE HR_CORE.SYSTEM_USERS ADD CONSTRAINT FK_USER_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_CORE.USER_ROLES ADD CONSTRAINT FK_UR_USER 
    FOREIGN KEY (USER_ID) REFERENCES HR_CORE.SYSTEM_USERS(USER_ID);

ALTER TABLE HR_CORE.USER_ROLES ADD CONSTRAINT FK_UR_ROLE 
    FOREIGN KEY (ROLE_ID) REFERENCES HR_CORE.SYSTEM_ROLES(ROLE_ID);

ALTER TABLE HR_CORE.ROLE_PERMISSIONS ADD CONSTRAINT FK_RP_ROLE 
    FOREIGN KEY (ROLE_ID) REFERENCES HR_CORE.SYSTEM_ROLES(ROLE_ID);

ALTER TABLE HR_CORE.ROLE_PERMISSIONS ADD CONSTRAINT FK_RP_PERM 
    FOREIGN KEY (PERMISSION_ID) REFERENCES HR_CORE.SYSTEM_PERMISSIONS(PERMISSION_ID);

-- Foreign Keys لجداول التدريب
ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRAINING ADD CONSTRAINT FK_TRAIN_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRAINING ADD CONSTRAINT FK_TRAIN_COURSE 
    FOREIGN KEY (COURSE_ID) REFERENCES HR_PERSONNEL.TRAINING_COURSES(COURSE_ID);

-- Foreign Keys لجداول المزايا
ALTER TABLE HR_PAYROLL.EMPLOYEE_INSURANCE ADD CONSTRAINT FK_INS_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.EMPLOYEE_INSURANCE ADD CONSTRAINT FK_INS_PLAN 
    FOREIGN KEY (PLAN_ID) REFERENCES HR_PAYROLL.INSURANCE_PLANS(PLAN_ID);

ALTER TABLE HR_PAYROLL.BONUSES ADD CONSTRAINT FK_BONUS_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.BONUSES ADD CONSTRAINT FK_BONUS_APPROVER 
    FOREIGN KEY (APPROVED_BY) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.BONUSES ADD CONSTRAINT FK_BONUS_RUN 
    FOREIGN KEY (PAYROLL_RUN_ID) REFERENCES HR_PAYROLL.PAYROLL_RUNS(RUN_ID);

-- Foreign Keys لجداول الأصول
ALTER TABLE HR_CORE.COMPANY_ASSETS ADD CONSTRAINT FK_ASSET_CAT 
    FOREIGN KEY (CATEGORY_ID) REFERENCES HR_CORE.ASSET_CATEGORIES(CATEGORY_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_ASSETS ADD CONSTRAINT FK_EASSET_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_ASSETS ADD CONSTRAINT FK_EASSET_ASSET 
    FOREIGN KEY (ASSET_ID) REFERENCES HR_CORE.COMPANY_ASSETS(ASSET_ID);

-- Foreign Keys لجدول النقل
ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS ADD CONSTRAINT FK_TRANS_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS ADD CONSTRAINT FK_TRANS_FROM_DEPT 
    FOREIGN KEY (FROM_DEPT_ID) REFERENCES HR_CORE.DEPARTMENTS(DEPT_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS ADD CONSTRAINT FK_TRANS_TO_DEPT 
    FOREIGN KEY (TO_DEPT_ID) REFERENCES HR_CORE.DEPARTMENTS(DEPT_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS ADD CONSTRAINT FK_TRANS_FROM_JOB 
    FOREIGN KEY (FROM_JOB_ID) REFERENCES HR_CORE.JOBS(JOB_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS ADD CONSTRAINT FK_TRANS_TO_JOB 
    FOREIGN KEY (TO_JOB_ID) REFERENCES HR_CORE.JOBS(JOB_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_TRANSFERS ADD CONSTRAINT FK_TRANS_APPROVER 
    FOREIGN KEY (APPROVED_BY) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

COMMIT;

PROMPT ========================================
PROMPT تم إضافة جميع Foreign Keys للجداول الجديدة!
PROMPT ========================================

-- التحقق من عدد Foreign Keys
SELECT owner, COUNT(*) as fk_count 
FROM all_constraints 
WHERE owner IN ('HR_CORE', 'HR_PERSONNEL', 'HR_ATTENDANCE', 'HR_LEAVES', 'HR_PAYROLL', 'HR_RECRUITMENT', 'HR_PERFORMANCE')
AND constraint_type = 'R'
GROUP BY owner
ORDER BY owner;

SELECT 'إجمالي Foreign Keys: ' || COUNT(*) AS TOTAL_FKS
FROM all_constraints 
WHERE owner IN ('HR_CORE', 'HR_PERSONNEL', 'HR_ATTENDANCE', 'HR_LEAVES', 'HR_PAYROLL', 'HR_RECRUITMENT', 'HR_PERFORMANCE')
AND constraint_type = 'R';
