-- =================================================================================
-- سكربت إضافة Foreign Keys لجميع الجداول
-- يجب تنفيذه بعد إنشاء جميع الجداول بنجاح
-- =================================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;

PROMPT ========================================
PROMPT منح الصلاحيات بين الـ Schemas
PROMPT ========================================

-- منح صلاحيات HR_CORE للجميع
GRANT REFERENCES, SELECT ON HR_CORE.COUNTRIES TO HR_PERSONNEL, HR_RECRUITMENT;
GRANT REFERENCES, SELECT ON HR_CORE.CITIES TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_CORE.DEPARTMENTS TO HR_PERSONNEL, HR_RECRUITMENT, HR_ATTENDANCE, HR_PAYROLL, HR_PERFORMANCE;
GRANT REFERENCES, SELECT ON HR_CORE.JOBS TO HR_PERSONNEL, HR_RECRUITMENT, HR_PAYROLL, HR_ATTENDANCE;
GRANT REFERENCES, SELECT ON HR_CORE.JOB_GRADES TO HR_PERSONNEL, HR_PAYROLL;
GRANT REFERENCES, SELECT ON HR_CORE.DOCUMENT_TYPES TO HR_PERSONNEL;
GRANT REFERENCES, SELECT ON HR_CORE.BANKS TO HR_PERSONNEL, HR_PAYROLL;

-- منح صلاحيات HR_PERSONNEL للوحدات الأخرى
GRANT REFERENCES, SELECT ON HR_PERSONNEL.EMPLOYEES TO HR_RECRUITMENT, HR_ATTENDANCE, HR_LEAVES, HR_PAYROLL, HR_PERFORMANCE, HR_CORE;
GRANT REFERENCES, SELECT ON HR_PERSONNEL.CONTRACTS TO HR_PAYROLL;

-- منح صلاحيات HR_ATTENDANCE
GRANT REFERENCES, SELECT ON HR_ATTENDANCE.SHIFT_TYPES TO HR_PERSONNEL, HR_ATTENDANCE;
GRANT REFERENCES, SELECT ON HR_ATTENDANCE.DAILY_ATTENDANCE TO HR_PAYROLL;

-- منح صلاحيات HR_LEAVES
GRANT REFERENCES, SELECT ON HR_LEAVES.LEAVE_TYPES TO HR_PERSONNEL, HR_LEAVES;
GRANT REFERENCES, SELECT ON HR_LEAVES.LEAVE_REQUESTS TO HR_ATTENDANCE, HR_PAYROLL;

-- منح صلاحيات HR_PAYROLL
GRANT REFERENCES, SELECT ON HR_PAYROLL.SALARY_ELEMENTS TO HR_PAYROLL;
GRANT REFERENCES, SELECT ON HR_PAYROLL.LOANS TO HR_PAYROLL;
GRANT REFERENCES, SELECT ON HR_PAYROLL.PAYROLL_RUNS TO HR_PAYROLL, HR_LEAVES;

-- منح صلاحيات HR_RECRUITMENT
GRANT REFERENCES, SELECT ON HR_RECRUITMENT.JOB_VACANCIES TO HR_RECRUITMENT;
GRANT REFERENCES, SELECT ON HR_RECRUITMENT.CANDIDATES TO HR_RECRUITMENT;
GRANT REFERENCES, SELECT ON HR_RECRUITMENT.APPLICATIONS TO HR_RECRUITMENT;

-- منح صلاحيات HR_PERFORMANCE
GRANT REFERENCES, SELECT ON HR_PERFORMANCE.KPI_LIBRARIES TO HR_PERFORMANCE;
GRANT REFERENCES, SELECT ON HR_PERFORMANCE.APPRAISAL_CYCLES TO HR_PERFORMANCE;
GRANT REFERENCES, SELECT ON HR_PERFORMANCE.EMPLOYEE_APPRAISALS TO HR_PERFORMANCE;
GRANT REFERENCES, SELECT ON HR_PERFORMANCE.VIOLATION_TYPES TO HR_PERFORMANCE;
GRANT REFERENCES, SELECT ON HR_PERFORMANCE.DISCIPLINARY_ACTIONS TO HR_PAYROLL, HR_PERFORMANCE;

PROMPT تم منح الصلاحيات بنجاح

PROMPT ========================================
PROMPT إضافة Foreign Keys لـ HR_CORE
PROMPT ========================================

ALTER TABLE HR_CORE.CITIES ADD CONSTRAINT FK_CITY_COUNTRY 
    FOREIGN KEY (COUNTRY_ID) REFERENCES HR_CORE.COUNTRIES(COUNTRY_ID);

ALTER TABLE HR_CORE.BRANCHES ADD CONSTRAINT FK_BRANCH_CITY 
    FOREIGN KEY (CITY_ID) REFERENCES HR_CORE.CITIES(CITY_ID);

ALTER TABLE HR_CORE.DEPARTMENTS ADD CONSTRAINT FK_DEPT_PARENT 
    FOREIGN KEY (PARENT_DEPT_ID) REFERENCES HR_CORE.DEPARTMENTS(DEPT_ID);

ALTER TABLE HR_CORE.DEPARTMENTS ADD CONSTRAINT FK_DEPT_BRANCH 
    FOREIGN KEY (BRANCH_ID) REFERENCES HR_CORE.BRANCHES(BRANCH_ID);

ALTER TABLE HR_CORE.JOBS ADD CONSTRAINT FK_JOB_GRADE 
    FOREIGN KEY (DEFAULT_GRADE_ID) REFERENCES HR_CORE.JOB_GRADES(GRADE_ID);

PROMPT تم إضافة Foreign Keys لـ HR_CORE

PROMPT ========================================
PROMPT إضافة Foreign Keys لـ HR_PERSONNEL
PROMPT ========================================

ALTER TABLE HR_PERSONNEL.EMPLOYEES ADD CONSTRAINT FK_EMP_NATIONALITY 
    FOREIGN KEY (NATIONALITY_ID) REFERENCES HR_CORE.COUNTRIES(COUNTRY_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEES ADD CONSTRAINT FK_EMP_JOB 
    FOREIGN KEY (JOB_ID) REFERENCES HR_CORE.JOBS(JOB_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEES ADD CONSTRAINT FK_EMP_DEPT 
    FOREIGN KEY (DEPT_ID) REFERENCES HR_CORE.DEPARTMENTS(DEPT_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEES ADD CONSTRAINT FK_EMP_MANAGER 
    FOREIGN KEY (MANAGER_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_DOCUMENTS ADD CONSTRAINT FK_DOC_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_DOCUMENTS ADD CONSTRAINT FK_DOC_TYPE 
    FOREIGN KEY (DOC_TYPE_ID) REFERENCES HR_CORE.DOCUMENT_TYPES(DOC_TYPE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_QUALIFICATIONS ADD CONSTRAINT FK_QUAL_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_QUALIFICATIONS ADD CONSTRAINT FK_QUAL_COUNTRY 
    FOREIGN KEY (COUNTRY_ID) REFERENCES HR_CORE.COUNTRIES(COUNTRY_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_EXPERIENCES ADD CONSTRAINT FK_EXP_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_CERTIFICATIONS ADD CONSTRAINT FK_CERT_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_ADDRESSES ADD CONSTRAINT FK_ADDR_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_ADDRESSES ADD CONSTRAINT FK_ADDR_CITY 
    FOREIGN KEY (CITY_ID) REFERENCES HR_CORE.CITIES(CITY_ID);

ALTER TABLE HR_PERSONNEL.EMERGENCY_CONTACTS ADD CONSTRAINT FK_EMERG_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_BANK_ACCOUNTS ADD CONSTRAINT FK_BANK_ACC_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.EMPLOYEE_BANK_ACCOUNTS ADD CONSTRAINT FK_BANK_ACC_BANK 
    FOREIGN KEY (BANK_ID) REFERENCES HR_CORE.BANKS(BANK_ID);

ALTER TABLE HR_PERSONNEL.CONTRACTS ADD CONSTRAINT FK_CONT_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERSONNEL.CONTRACT_RENEWALS ADD CONSTRAINT FK_RENEW_CONT 
    FOREIGN KEY (CONTRACT_ID) REFERENCES HR_PERSONNEL.CONTRACTS(CONTRACT_ID);

ALTER TABLE HR_PERSONNEL.DEPENDENTS ADD CONSTRAINT FK_DEP_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

PROMPT تم إضافة Foreign Keys لـ HR_PERSONNEL

PROMPT ========================================
PROMPT إضافة Foreign Keys لـ HR_ATTENDANCE
PROMPT ========================================

ALTER TABLE HR_ATTENDANCE.EMPLOYEE_ROSTERS ADD CONSTRAINT FK_ROSTER_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_ATTENDANCE.EMPLOYEE_ROSTERS ADD CONSTRAINT FK_ROSTER_SHIFT 
    FOREIGN KEY (SHIFT_ID) REFERENCES HR_ATTENDANCE.SHIFT_TYPES(SHIFT_ID);

ALTER TABLE HR_ATTENDANCE.RAW_PUNCH_LOGS ADD CONSTRAINT FK_LOG_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_ATTENDANCE.DAILY_ATTENDANCE ADD CONSTRAINT FK_DAILY_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_ATTENDANCE.DAILY_ATTENDANCE ADD CONSTRAINT FK_DAILY_SHIFT 
    FOREIGN KEY (PLANNED_SHIFT_ID) REFERENCES HR_ATTENDANCE.SHIFT_TYPES(SHIFT_ID);

ALTER TABLE HR_ATTENDANCE.SHIFT_SWAP_REQUESTS ADD CONSTRAINT FK_SWAP_REQ 
    FOREIGN KEY (REQUESTER_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_ATTENDANCE.SHIFT_SWAP_REQUESTS ADD CONSTRAINT FK_SWAP_TARGET 
    FOREIGN KEY (TARGET_EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_ATTENDANCE.OVERTIME_REQUESTS ADD CONSTRAINT FK_OT_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_ATTENDANCE.OVERTIME_REQUESTS ADD CONSTRAINT FK_OT_APPROVER 
    FOREIGN KEY (APPROVED_BY) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_ATTENDANCE.ATTENDANCE_POLICIES ADD CONSTRAINT FK_POL_DEPT 
    FOREIGN KEY (DEPT_ID) REFERENCES HR_CORE.DEPARTMENTS(DEPT_ID);

ALTER TABLE HR_ATTENDANCE.ATTENDANCE_POLICIES ADD CONSTRAINT FK_POL_JOB 
    FOREIGN KEY (JOB_ID) REFERENCES HR_CORE.JOBS(JOB_ID);

PROMPT تم إضافة Foreign Keys لـ HR_ATTENDANCE

PROMPT ========================================
PROMPT إضافة Foreign Keys لـ HR_LEAVES
PROMPT ========================================

ALTER TABLE HR_LEAVES.EMPLOYEE_LEAVE_BALANCES ADD CONSTRAINT FK_BAL_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_LEAVES.EMPLOYEE_LEAVE_BALANCES ADD CONSTRAINT FK_BAL_TYPE 
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES HR_LEAVES.LEAVE_TYPES(LEAVE_TYPE_ID);

ALTER TABLE HR_LEAVES.LEAVE_REQUESTS ADD CONSTRAINT FK_REQ_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_LEAVES.LEAVE_REQUESTS ADD CONSTRAINT FK_REQ_TYPE 
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES HR_LEAVES.LEAVE_TYPES(LEAVE_TYPE_ID);

ALTER TABLE HR_LEAVES.LEAVE_ACCRUAL_RULES ADD CONSTRAINT FK_ACCR_TYPE 
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES HR_LEAVES.LEAVE_TYPES(LEAVE_TYPE_ID);

ALTER TABLE HR_LEAVES.LEAVE_ENCASHMENT ADD CONSTRAINT FK_ENCASH_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_LEAVES.LEAVE_ENCASHMENT ADD CONSTRAINT FK_ENCASH_TYPE 
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES HR_LEAVES.LEAVE_TYPES(LEAVE_TYPE_ID);

ALTER TABLE HR_LEAVES.LEAVE_TRANSACTIONS ADD CONSTRAINT FK_TRANS_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_LEAVES.LEAVE_TRANSACTIONS ADD CONSTRAINT FK_TRANS_TYPE 
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES HR_LEAVES.LEAVE_TYPES(LEAVE_TYPE_ID);

PROMPT تم إضافة Foreign Keys لـ HR_LEAVES

PROMPT ========================================
PROMPT إضافة Foreign Keys لـ HR_PAYROLL
PROMPT ========================================

ALTER TABLE HR_PAYROLL.EMPLOYEE_SALARY_STRUCTURE ADD CONSTRAINT FK_STRUCT_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.EMPLOYEE_SALARY_STRUCTURE ADD CONSTRAINT FK_STRUCT_ELEM 
    FOREIGN KEY (ELEMENT_ID) REFERENCES HR_PAYROLL.SALARY_ELEMENTS(ELEMENT_ID);

ALTER TABLE HR_PAYROLL.LOANS ADD CONSTRAINT FK_LOAN_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.LOAN_INSTALLMENTS ADD CONSTRAINT FK_INST_LOAN 
    FOREIGN KEY (LOAN_ID) REFERENCES HR_PAYROLL.LOANS(LOAN_ID);

ALTER TABLE HR_PAYROLL.PAYSLIPS ADD CONSTRAINT FK_SLIP_RUN 
    FOREIGN KEY (RUN_ID) REFERENCES HR_PAYROLL.PAYROLL_RUNS(RUN_ID);

ALTER TABLE HR_PAYROLL.PAYSLIPS ADD CONSTRAINT FK_SLIP_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.PAYSLIP_DETAILS ADD CONSTRAINT FK_DETAIL_SLIP 
    FOREIGN KEY (PAYSLIP_ID) REFERENCES HR_PAYROLL.PAYSLIPS(PAYSLIP_ID);

ALTER TABLE HR_PAYROLL.END_OF_SERVICE_CALC ADD CONSTRAINT FK_EOS_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.PAYROLL_ADJUSTMENTS ADD CONSTRAINT FK_ADJ_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PAYROLL.PAYROLL_ADJUSTMENTS ADD CONSTRAINT FK_ADJ_RUN 
    FOREIGN KEY (PAYROLL_RUN_ID) REFERENCES HR_PAYROLL.PAYROLL_RUNS(RUN_ID);

PROMPT تم إضافة Foreign Keys لـ HR_PAYROLL

PROMPT ========================================
PROMPT إضافة Foreign Keys لـ HR_RECRUITMENT
PROMPT ========================================

ALTER TABLE HR_RECRUITMENT.JOB_VACANCIES ADD CONSTRAINT FK_VAC_JOB 
    FOREIGN KEY (JOB_ID) REFERENCES HR_CORE.JOBS(JOB_ID);

ALTER TABLE HR_RECRUITMENT.JOB_VACANCIES ADD CONSTRAINT FK_VAC_DEPT 
    FOREIGN KEY (DEPT_ID) REFERENCES HR_CORE.DEPARTMENTS(DEPT_ID);

ALTER TABLE HR_RECRUITMENT.CANDIDATES ADD CONSTRAINT FK_CAND_NAT 
    FOREIGN KEY (NATIONALITY_ID) REFERENCES HR_CORE.COUNTRIES(COUNTRY_ID);

ALTER TABLE HR_RECRUITMENT.APPLICATIONS ADD CONSTRAINT FK_APP_VAC 
    FOREIGN KEY (VACANCY_ID) REFERENCES HR_RECRUITMENT.JOB_VACANCIES(VACANCY_ID);

ALTER TABLE HR_RECRUITMENT.APPLICATIONS ADD CONSTRAINT FK_APP_CAND 
    FOREIGN KEY (CANDIDATE_ID) REFERENCES HR_RECRUITMENT.CANDIDATES(CANDIDATE_ID);

ALTER TABLE HR_RECRUITMENT.INTERVIEWS ADD CONSTRAINT FK_INT_APP 
    FOREIGN KEY (APP_ID) REFERENCES HR_RECRUITMENT.APPLICATIONS(APP_ID);

ALTER TABLE HR_RECRUITMENT.INTERVIEWS ADD CONSTRAINT FK_INT_EMP 
    FOREIGN KEY (INTERVIEWER_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_RECRUITMENT.OFFERS ADD CONSTRAINT FK_OFFER_APP 
    FOREIGN KEY (APP_ID) REFERENCES HR_RECRUITMENT.APPLICATIONS(APP_ID);

PROMPT تم إضافة Foreign Keys لـ HR_RECRUITMENT

PROMPT ========================================
PROMPT إضافة Foreign Keys لـ HR_PERFORMANCE
PROMPT ========================================

ALTER TABLE HR_PERFORMANCE.EMPLOYEE_APPRAISALS ADD CONSTRAINT FK_APPR_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERFORMANCE.EMPLOYEE_APPRAISALS ADD CONSTRAINT FK_APPR_CYCLE 
    FOREIGN KEY (CYCLE_ID) REFERENCES HR_PERFORMANCE.APPRAISAL_CYCLES(CYCLE_ID);

ALTER TABLE HR_PERFORMANCE.EMPLOYEE_APPRAISALS ADD CONSTRAINT FK_APPR_EVAL 
    FOREIGN KEY (EVALUATOR_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERFORMANCE.APPRAISAL_DETAILS ADD CONSTRAINT FK_DET_APPR 
    FOREIGN KEY (APPRAISAL_ID) REFERENCES HR_PERFORMANCE.EMPLOYEE_APPRAISALS(APPRAISAL_ID);

ALTER TABLE HR_PERFORMANCE.APPRAISAL_DETAILS ADD CONSTRAINT FK_DET_KPI 
    FOREIGN KEY (KPI_ID) REFERENCES HR_PERFORMANCE.KPI_LIBRARIES(KPI_ID);

ALTER TABLE HR_PERFORMANCE.EMPLOYEE_VIOLATIONS ADD CONSTRAINT FK_VIOL_EMP 
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES HR_PERSONNEL.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE HR_PERFORMANCE.EMPLOYEE_VIOLATIONS ADD CONSTRAINT FK_VIOL_TYPE 
    FOREIGN KEY (VIOLATION_TYPE_ID) REFERENCES HR_PERFORMANCE.VIOLATION_TYPES(VIOLATION_TYPE_ID);

ALTER TABLE HR_PERFORMANCE.EMPLOYEE_VIOLATIONS ADD CONSTRAINT FK_VIOL_ACTION 
    FOREIGN KEY (ACTION_ID) REFERENCES HR_PERFORMANCE.DISCIPLINARY_ACTIONS(ACTION_ID);

PROMPT تم إضافة Foreign Keys لـ HR_PERFORMANCE

PROMPT ========================================
PROMPT اكتمل إضافة جميع Foreign Keys!
PROMPT ========================================

-- التحقق من عدد Foreign Keys
SELECT owner, COUNT(*) as fk_count 
FROM all_constraints 
WHERE owner IN ('HR_CORE', 'HR_PERSONNEL', 'HR_ATTENDANCE', 'HR_LEAVES', 'HR_PAYROLL', 'HR_RECRUITMENT', 'HR_PERFORMANCE')
AND constraint_type = 'R'
GROUP BY owner
ORDER BY owner;

SELECT 'تم إضافة ' || COUNT(*) || ' Foreign Key بنجاح!' AS FINAL_STATUS
FROM all_constraints 
WHERE owner IN ('HR_CORE', 'HR_PERSONNEL', 'HR_ATTENDANCE', 'HR_LEAVES', 'HR_PAYROLL', 'HR_RECRUITMENT', 'HR_PERFORMANCE')
AND constraint_type = 'R';
