-- =================================================================================
-- إنشاء Synonyms لتسهيل الوصول لجميع الجداول
-- بدلاً من كتابة HR_PERSONNEL.EMPLOYEES يمكنك كتابة EMPLOYEES فقط
-- =================================================================================

ALTER SESSION SET CONTAINER = XEPDB1;

-- Synonyms لجداول HR_CORE
CREATE OR REPLACE PUBLIC SYNONYM COUNTRIES FOR HR_CORE.COUNTRIES;
CREATE OR REPLACE PUBLIC SYNONYM CITIES FOR HR_CORE.CITIES;
CREATE OR REPLACE PUBLIC SYNONYM DEPARTMENTS FOR HR_CORE.DEPARTMENTS;
CREATE OR REPLACE PUBLIC SYNONYM JOBS FOR HR_CORE.JOBS;
CREATE OR REPLACE PUBLIC SYNONYM BANKS FOR HR_CORE.BANKS;

-- Synonyms لجداول HR_PERSONNEL
CREATE OR REPLACE PUBLIC SYNONYM EMPLOYEES FOR HR_PERSONNEL.EMPLOYEES;
CREATE OR REPLACE PUBLIC SYNONYM CONTRACTS FOR HR_PERSONNEL.CONTRACTS;
CREATE OR REPLACE PUBLIC SYNONYM EMPLOYEE_DOCUMENTS FOR HR_PERSONNEL.EMPLOYEE_DOCUMENTS;

-- Synonyms لجداول HR_ATTENDANCE
CREATE OR REPLACE PUBLIC SYNONYM DAILY_ATTENDANCE FOR HR_ATTENDANCE.DAILY_ATTENDANCE;
CREATE OR REPLACE PUBLIC SYNONYM SHIFT_TYPES FOR HR_ATTENDANCE.SHIFT_TYPES;

-- Synonyms لجداول HR_LEAVES
CREATE OR REPLACE PUBLIC SYNONYM LEAVE_REQUESTS FOR HR_LEAVES.LEAVE_REQUESTS;
CREATE OR REPLACE PUBLIC SYNONYM LEAVE_TYPES FOR HR_LEAVES.LEAVE_TYPES;

-- Synonyms لجداول HR_PAYROLL
CREATE OR REPLACE PUBLIC SYNONYM PAYSLIPS FOR HR_PAYROLL.PAYSLIPS;
CREATE OR REPLACE PUBLIC SYNONYM PAYROLL_RUNS FOR HR_PAYROLL.PAYROLL_RUNS;

SELECT 'تم إنشاء Synonyms بنجاح! الآن يمكنك استخدام SELECT * FROM EMPLOYEES مباشرة' AS STATUS FROM DUAL;
